// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using TicketDetalle.Server.DAL;

#nullable disable

namespace TicketDetalle.Server.Migrations
{
    [DbContext(typeof(Context))]
    partial class ContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.12");

            modelBuilder.Entity("TicketDetalles", b =>
                {
                    b.Property<int>("TicketDetalleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("emisor")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("mensaje")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TicketDetalleId");

                    b.ToTable("TicketDetalles");
                });
#pragma warning restore 612, 618
        }
    }
}
